### PR TITLE
Client as facade and added readers and writers

### PR DESCRIPTION
**Pull request by wdalmut**
Actually we have a major issue with the actual design. We cannot use the
same client instance for writing data points using UDP/IP and read data
using the HTTP client. This is because the `adapter` section is designed
as a big block with 2 responsibility per adapter: reading for data and
write information back to InfluxDB:

```php
$adapter = new UdpAdapter(...);
$client = new Client($adapter);
```

Because the Udp/Ip adapter is only `Writeable` we cannot use this
`$client` instance in order to performs also the read operation, we have
to create another client that uses the HTTP adapter and we will force
users to have 2 clients in the application.

This feature allows the final user to mount a `Writer` and a `Reader` in
order to perform completely separate operation in order to select with
writer driver is the best one for the actual user story and the reader
implementation:

```php
$writer = new Udp\Writer(...);
$reader = new Http\Reader(...);

$client = new Client($reader, $writer);
```

Now the `$client` instance performs both operation: `mark` and `query`
using the Udp\Ip adapter for write information and the HTTP adapter for
read back data.

The drawback that is the library composition now is a bit harder (again)
because of this composition.

This step could be also interesting in order to refactor the actual
**Test Suite** that is effectively a bit pointless and obfuscate
different library goals.

### CODE REVIEW

**Comment by wdalmut** [comment]
## BC BREAK

 * Removed factory method (let to the user the library composition)
 * Moved to Reader and Writers in order to use a single client instance (client as facade)

**Comment by wdalmut** [comment]
do you like this approach?

:+1:

**Comment by gianarb** [comment]
Yes! it is a good way to increase the client's role and to split responsibilities

**Comment by wdalmut** [comment]
@gianarb i think that we can merge this.

**Comment by skynet** [comment]
:+1: I still have to test this.

**Pull request merged**
