### PR TITLE
Implemented comma, equal sign and space escaping

### PR DESCRIPTION
**Pull request by Zwartpet**
Implemented escaping for tag keys/values and measurement keys
https://docs.influxdata.com/influxdb/v1.2/write_protocols/line_protocol_reference/#special-characters

### CODE REVIEW

**Comment by wdalmut** [comment]
Thanks for your PR.

we will review this asap. 

At first sight i think that this escape procedure should go in the `WriterTrait` and not in the `Client`.

**Comment by Zwartpet** [comment]
@wdalmut Moved it to the WriterTrait as requested ;)

**Comment by Zwartpet** [comment]
Ah, didn't pay attention there, reverted the client.php to master.

**Comment by wdalmut** [comment]
I think that is all good. Can you just squash your 4 commits to a single commit?

**Comment by Zwartpet** [comment]
I certainly can

**Comment by wdalmut** [comment]
:+1:  thank you so much!

**Pull request merged**
