### PR TITLE
Feature/influxdb 0.9

### PR DESCRIPTION
**Pull request by wdalmut**

### CODE REVIEW

**Comment by wdalmut** [comment]
InfluxDB configuration changes also in RC32

**Comment by wdalmut** [comment]
Sadly RC 32 uses a complete different UDP/IP message format

```
cpu,region=us-west,host=serverA,env=prod,target=servers,zone=1c,tag1=value1,tag2=value2,tag3=value3,tag4=value4,tag5=value5 value=1 1000000000
```

**Comment by wdalmut** [comment]
Compatible with InfluxDB release candidate 33

**Comment by wdalmut** [comment]
@gianarb ready to merge imho

**Comment by gianarb** [comment]
Go go go!!

**Pull request merged**
